[calltoagent]
exten => s,1,NoOp(Starting call to agent)
same => n,NoOp(callid=${callid})
same => n,Set(AGENT_NUMBER=${agent_number})
same => n,Dial(PJSIP/${AGENT_NUMBER},30)
same => n,Hangup()

exten => h,1,NoOp(Call to agent ended)
same => n,NoOp(callid=${callid})
same => n,NoOp(hangupcause=${HANGUPCAUSE})
same => n,NoOp(hangupsource=${CHANNEL(hangupsource)})


[calltouser]
exten => s,1,NoOp(Starting call to user)
same => n,Set(USER_NUMBER=${user_number})
same => n,Set(CALLERID(num)=${agent_number})
same => n,Dial(PJSIP/${USER_NUMBER},30)
same => n,Hangup()
